/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurante_pro.menu_opciones;
 
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import restaurante_pro.Iniciar_Sesion;
import restaurante_pro.conectarbd;

/**
 *
 * @author stikeroox
 */
public class Encargado_comanda extends javax.swing.JFrame {
    DefaultTableModel modelo = new DefaultTableModel();
    
        PreparedStatement ps;
        ResultSet  rs;
    /**
     * Creates new form Encargado_comanda
     */
    public Encargado_comanda() {
        initComponents();
        setLocationRelativeTo( null );
        setTitle("Encargado de comandas");
         modelo.addColumn("Nombre_Platillo");
         modelo.addColumn("Cantidad");
         modelo.addColumn("Precio");
         
         modelo.addColumn("Nume_orden");
        
        tablac.setModel(modelo);
         
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        numorden = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nuevo = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        pasta = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablac = new javax.swing.JTable();
        canpasta = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        prepasta = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        mesero = new javax.swing.JTextField();
        Cliente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ensalada = new javax.swing.JCheckBox();
        canensalada = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        preensalada = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        milanesa = new javax.swing.JCheckBox();
        canmilanesa = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        premilanesa = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        pescado = new javax.swing.JCheckBox();
        canpescado = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        prepescado = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        elote = new javax.swing.JCheckBox();
        canelote = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        fruta = new javax.swing.JCheckBox();
        flan = new javax.swing.JCheckBox();
        canflan = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        canfru = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        preflan = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        prefru = new javax.swing.JComboBox();
        preelote = new javax.swing.JComboBox();
        jLabel20 = new javax.swing.JLabel();
        helado = new javax.swing.JCheckBox();
        canhe = new javax.swing.JComboBox();
        jLabel21 = new javax.swing.JLabel();
        prehe = new javax.swing.JComboBox();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        Whyski = new javax.swing.JCheckBox();
        canwh = new javax.swing.JComboBox();
        jLabel24 = new javax.swing.JLabel();
        coca = new javax.swing.JCheckBox();
        nombrev = new javax.swing.JCheckBox();
        cantidav = new javax.swing.JComboBox();
        jLabel25 = new javax.swing.JLabel();
        cancoca = new javax.swing.JComboBox();
        jLabel26 = new javax.swing.JLabel();
        preciov = new javax.swing.JComboBox();
        jLabel27 = new javax.swing.JLabel();
        precoca = new javax.swing.JComboBox();
        pw = new javax.swing.JComboBox();
        jLabel28 = new javax.swing.JLabel();
        cafe = new javax.swing.JCheckBox();
        canca = new javax.swing.JComboBox();
        jLabel29 = new javax.swing.JLabel();
        preca = new javax.swing.JComboBox();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        mesa = new javax.swing.JComboBox();
        jLabel41 = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Mesa");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel2.setText("Mesero");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, 24));

        nuevo.setText("Nuevo");
        nuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nuevoMouseClicked(evt);
            }
        });
        nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoActionPerformed(evt);
            }
        });
        getContentPane().add(nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 70, -1));

        jButton2.setText("Registrar pedido");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 120, -1));

        jButton3.setText("Salir");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 86, -1));

        jLabel8.setText("Cliente");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, -1));

        pasta.setText("Spaguetti");
        pasta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pastaActionPerformed(evt);
            }
        });
        getContentPane().add(pasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, -1, -1));

        tablac.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre_Platillo", "Cantidad", "Precio", "nume_orden"
            }
        ));
        jScrollPane1.setViewportView(tablac);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 254, 118));

        canpasta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        getContentPane().add(canpasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 47, -1));

        jLabel4.setText("Cantidad");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, -1, -1));

        prepasta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "80" }));
        getContentPane().add(prepasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 47, -1));

        jLabel5.setText("Precio");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 50, -1));

        mesero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meseroActionPerformed(evt);
            }
        });
        getContentPane().add(mesero, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 46, -1));
        getContentPane().add(Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 50, -1));

        jLabel6.setText("Registro de comanda");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel7.setText("Precio");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 50, -1));

        ensalada.setText("Ensalada");
        getContentPane().add(ensalada, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, -1, -1));

        canensalada.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        getContentPane().add(canensalada, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 47, -1));

        jLabel9.setText("Cantidad");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, -1, -1));

        preensalada.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "50", "75", "100" }));
        getContentPane().add(preensalada, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 47, -1));

        jLabel10.setText("Precio");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, 50, -1));

        milanesa.setText("Milanesa");
        milanesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                milanesaActionPerformed(evt);
            }
        });
        getContentPane().add(milanesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, -1, -1));

        canmilanesa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        getContentPane().add(canmilanesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 150, 47, -1));

        jLabel11.setText("Cantidad");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, -1, -1));

        premilanesa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "50", "75", "100" }));
        getContentPane().add(premilanesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 180, 47, -1));

        jLabel12.setText("Precio");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 180, 50, -1));

        pescado.setText("Pescado marinado");
        getContentPane().add(pescado, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 120, -1, -1));

        canpescado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        getContentPane().add(canpescado, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 150, 79, -1));

        jLabel13.setText("Cantidad");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 150, -1, -1));

        prepescado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "50", "75", "100" }));
        getContentPane().add(prepescado, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 180, 79, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 103, 10));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 103, 10));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 210, 103, 10));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 210, 127, 20));

        jLabel14.setText("Precio");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, 50, -1));

        jLabel15.setText("Precio");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 380, 50, -1));

        elote.setText("Pastel de chocolate");
        getContentPane().add(elote, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, -1, -1));

        canelote.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        getContentPane().add(canelote, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 340, 47, -1));

        jLabel16.setText("Precio");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 380, 50, -1));

        fruta.setText("Dona de tocino");
        fruta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frutaActionPerformed(evt);
            }
        });
        getContentPane().add(fruta, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 310, 114, -1));

        flan.setText("Flan napolitano");
        getContentPane().add(flan, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, -1, -1));

        canflan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        getContentPane().add(canflan, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, 47, -1));

        jLabel17.setText("Cantidad");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, -1, -1));

        canfru.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        getContentPane().add(canfru, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 340, 47, -1));

        jLabel18.setText("Cantidad");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 340, -1, -1));

        preflan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "50", "75", "100" }));
        getContentPane().add(preflan, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 47, -1));

        jLabel19.setText("Cantidad");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, -1, -1));

        prefru.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "50", "75", "100" }));
        getContentPane().add(prefru, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 370, 47, -1));

        preelote.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "50", "75", "100" }));
        getContentPane().add(preelote, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, 47, -1));

        jLabel20.setText("Precio");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 380, 50, -1));

        helado.setText("Helado Capuchino ");
        helado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heladoActionPerformed(evt);
            }
        });
        getContentPane().add(helado, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 310, 112, -1));

        canhe.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        getContentPane().add(canhe, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 340, 46, -1));

        jLabel21.setText("Cantidad");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 340, -1, -1));

        prehe.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "50", "75", "100" }));
        getContentPane().add(prehe, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 370, 46, -1));
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, 113, 10));
        getContentPane().add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 410, 112, 10));
        getContentPane().add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 410, 114, 10));
        getContentPane().add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 410, 102, 10));

        jLabel22.setText("Precio");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 560, 50, 20));

        jLabel23.setText("Precio");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 560, 50, 20));

        Whyski.setText("whisky");
        getContentPane().add(Whyski, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 500, 103, -1));

        canwh.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        getContentPane().add(canwh, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 530, 47, -1));

        jLabel24.setText("Precio");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 570, 50, -1));

        coca.setText("Coca-cola");
        coca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cocaActionPerformed(evt);
            }
        });
        getContentPane().add(coca, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 500, 103, -1));

        nombrev.setText("Vino ");
        getContentPane().add(nombrev, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 500, -1, -1));

        cantidav.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        cantidav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidavActionPerformed(evt);
            }
        });
        getContentPane().add(cantidav, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 530, 47, -1));

        jLabel25.setText("Cantidad");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 540, -1, -1));

        cancoca.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        getContentPane().add(cancoca, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 530, 47, -1));

        jLabel26.setText("Cantidad");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 536, -1, 20));

        preciov.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "50", "75", "100" }));
        getContentPane().add(preciov, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 560, 47, -1));

        jLabel27.setText("Cantidad");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 540, -1, -1));

        precoca.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "50", "75", "100" }));
        getContentPane().add(precoca, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 560, 47, -1));

        pw.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "50", "75", "100" }));
        getContentPane().add(pw, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 560, 47, -1));

        jLabel28.setText("Precio");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 560, 50, -1));

        cafe.setText("Cafe ");
        cafe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cafeActionPerformed(evt);
            }
        });
        getContentPane().add(cafe, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 500, 112, -1));

        canca.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        getContentPane().add(canca, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 520, 46, -1));

        jLabel29.setText("Cantidad");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 530, -1, -1));

        preca.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "50", "75", "100" }));
        getContentPane().add(preca, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 560, 46, -1));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurante_pro/imagenes/coke_folder_file_10459.png"))); // NOI18N
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 430, -1, 62));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurante_pro/imagenes/coffee_22315.png"))); // NOI18N
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 420, 87, 78));

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurante_pro/imagenes/Wine_Bottle_icon-icons.com_68671.png"))); // NOI18N
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, 70, 56));

        jButton5.setText("Eliminar");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 80, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurante_pro/imagenes/Dish_Pasta_Spaghetti_26373.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 63, -1));

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurante_pro/imagenes/en.png"))); // NOI18N
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, 71, 80));

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurante_pro/imagenes/roast-leg-of-lamb_121481.png"))); // NOI18N
        jLabel35.setText("jLabel35");
        getContentPane().add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 57, 80, 60));

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurante_pro/imagenes/Fish_Dorada_26371.png"))); // NOI18N
        getContentPane().add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 50, 80, 67));

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurante_pro/imagenes/Drinks-03_icon-icons.com_61979.png"))); // NOI18N
        jLabel34.setText("jLabel34");
        getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 420, 76, -1));

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurante_pro/imagenes/32428custard_98919.png"))); // NOI18N
        getContentPane().add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, -1, -1));

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurante_pro/imagenes/Cake_ChocolateCake_26374.png"))); // NOI18N
        jLabel38.setText("jLabel38");
        getContentPane().add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 67, -1));

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurante_pro/imagenes/iconfinder-donutdoughnutstrawberrysnackdessertfastfoodfood-4306472_119917.png"))); // NOI18N
        getContentPane().add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 240, -1, -1));

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurante_pro/imagenes/-ice-cream_89753.png"))); // NOI18N
        jLabel40.setText("jLabel40");
        getContentPane().add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 240, 77, -1));

        mesa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        getContentPane().add(mesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurante_pro/imagenes/generatedtext (5).png"))); // NOI18N
        jLabel41.setText("jLabel41");
        getContentPane().add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 240, 80));

        id.setText("jLabel44");
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 220, 80));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurante_pro/imagenes/fondo_web_centfocs_restaurant-1024x761.jpg"))); // NOI18N
        fondo.setText("jLabel42");
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 800, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //metodos 
   
   
    
        
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code hereregistrar
                        String DATO[] = new String[4];//tabla para comida

      
        conectarbd con=new conectarbd();
        java.sql.Connection reg=con.getconexion();
     
       String sql = null;
              sql=("INSERT INTO comanda(Nombre_Platillo,Cantidad,Precio,Nume_orden)VALUES (?,?,?,?)");

try {
            //nada mas para el menu alv
            PreparedStatement pst=reg.prepareStatement(sql);
            
      if(pasta.isSelected()){
            pst.setString(1,pasta.getLabel());
            pst.setString(2,canpasta.getSelectedItem().toString());
            pst.setString(3,prepasta.getSelectedItem().toString());
              
               pst.setString(4,numorden.getText());
              
         
                     DATO[0] = pasta.getLabel();
                     DATO[1] = canpasta.getSelectedItem().toString();
                     DATO[2] = prepasta.getSelectedItem().toString();
                     
                     DATO[3] = numorden.getText();
                     
                  
                        modelo.addRow(DATO);}
          if(ensalada.isSelected()){
            pst.setString(1,ensalada.getLabel());
            pst.setString(2,canensalada.getSelectedItem().toString());
            pst.setString(3,preensalada.getSelectedItem().toString());
             
               pst.setString(4,numorden.getText());
               
         
                     DATO[0] = ensalada.getLabel();
                     DATO[1] = canensalada.getSelectedItem().toString();
                     DATO[2] = preensalada.getSelectedItem().toString();
                    
                     DATO[3] = numorden.getText();
                        modelo.addRow(DATO);
              }
           if(milanesa.isSelected()){
            pst.setString(1,milanesa.getLabel());
            pst.setString(2,canmilanesa.getSelectedItem().toString());
            pst.setString(3,premilanesa.getSelectedItem().toString());
               
               pst.setString(4,numorden.getText());
              
         
                     DATO[0] = pasta.getLabel();
                     DATO[1] = canpasta.getSelectedItem().toString();
                     DATO[2] = prepasta.getSelectedItem().toString();
                    
                     DATO[3] = numorden.getText();
                        modelo.addRow(DATO);
              }
           if(pescado.isSelected()){
            pst.setString(1,pescado.getLabel());
            pst.setString(2,canpescado.getSelectedItem().toString());
            pst.setString(3,prepescado.getSelectedItem().toString());
               
               pst.setString(4,numorden.getText());
         
                     DATO[0] = pescado.getLabel();
                     DATO[1] = canpescado.getSelectedItem().toString();
                     DATO[2] = prepescado.getSelectedItem().toString();
                    
                     DATO[3] = numorden.getText();
                   
                        modelo.addRow(DATO);
              }
           //tabla postres_------------------------------------
            if(flan.isSelected()){
            pst.setString(1,flan.getLabel());
            pst.setString(2,canflan.getSelectedItem().toString());
            pst.setString(3,preflan.getSelectedItem().toString());
              
               pst.setString(4,numorden.getText());
         
                     DATO[0] = flan.getLabel();
                     DATO[1] = canflan.getSelectedItem().toString();
                     DATO[2] = preflan.getSelectedItem().toString();
                     
                     DATO[3] = numorden.getText();
                     
                        modelo.addRow(DATO);}
           if(elote.isSelected()){
            pst.setString(1,elote.getLabel());
            pst.setString(2,canelote.getSelectedItem().toString());
            pst.setString(3,preelote.getSelectedItem().toString());
           
               pst.setString(4,numorden.getText());
         
                     DATO[0] = elote.getLabel();
                     DATO[1] = canelote.getSelectedItem().toString();
                     DATO[2] = preelote.getSelectedItem().toString();
                     
                     DATO[3] = numorden.getText();
                        modelo.addRow(DATO);
              }
            if(fruta.isSelected()){
                
            pst.setString(1,fruta.getLabel());
            pst.setString(2,canfru.getSelectedItem().toString());
            pst.setString(3,prefru.getSelectedItem().toString());
              
               pst.setString(4,numorden.getText());
         
                     DATO[0] = fruta.getLabel();
                     DATO[1] = canfru.getSelectedItem().toString();
                     DATO[2] = prefru.getSelectedItem().toString();
                    
                     DATO[3] = numorden.getText();
                        modelo.addRow(DATO);
              }
             if(helado.isSelected()){
            pst.setString(1,helado.getLabel());
            pst.setString(2,canhe.getSelectedItem().toString());
            pst.setString(3,prehe.getSelectedItem().toString());
             
               pst.setString(4,numorden.getText());
         
                     DATO[0] = helado.getLabel();
                     DATO[1] = canhe.getSelectedItem().toString();
                     DATO[2] = prehe.getSelectedItem().toString();
                     
                     DATO[3] = numorden.getText();
                        modelo.addRow(DATO);
              }
             //Tablapara bebidas
             if(nombrev.isSelected()){
            pst.setString(1,nombrev.getLabel());
            pst.setString(2,cantidav.getSelectedItem().toString());
            pst.setString(3,preciov.getSelectedItem().toString());
              
               pst.setString(4,numorden.getText());
         
                     DATO[0] = nombrev.getLabel();
                     DATO[1] = cantidav.getSelectedItem().toString();
                     DATO[2] = preciov.getSelectedItem().toString();
                     
                     DATO[3] = numorden.getText();
                        modelo.addRow(DATO);}
          if(Whyski.isSelected()){
           pst.setString(1,Whyski.getLabel());
            pst.setString(2,canwh.getSelectedItem().toString());
            pst.setString(3,pw.getSelectedItem().toString());
              
               pst.setString(4,numorden.getText());
         
                     DATO[0] = Whyski.getLabel();
                     DATO[1] = canwh.getSelectedItem().toString();
                     DATO[2] = pw.getSelectedItem().toString();
                     
                     DATO[3] = numorden.getText();
                        modelo.addRow(DATO);
              }
           if(coca.isSelected()){
            pst.setString(1,coca.getLabel());
            pst.setString(2,cancoca.getSelectedItem().toString());
            pst.setString(3,precoca.getSelectedItem().toString());
               
               pst.setString(4,numorden.getText());
         
                     DATO[0] = coca.getLabel();
                     DATO[1] = cancoca.getSelectedItem().toString();
                     DATO[2] = precoca.getSelectedItem().toString();
                   
                     DATO[3] = numorden.getText();
                        modelo.addRow(DATO);
              }
           if(cafe.isSelected()){
            pst.setString(1,cafe.getLabel());
            pst.setString(2,canca.getSelectedItem().toString());
            pst.setString(3,preca.getSelectedItem().toString());
              
               pst.setString(4,numorden.getText());
         
                     DATO[0] = pasta.getLabel();
                     DATO[1] = canca.getSelectedItem().toString();
                     DATO[2] = preca.getSelectedItem().toString();
                     
                     DATO[3] = numorden.getText();
                        modelo.addRow(DATO);
                        
              }
               
               
               

           
            
            int n=pst.executeUpdate();
            if (n>0){
                JOptionPane.showMessageDialog(null,"Pedido registrado correctamente");
              
                
            }
            
            
       } catch (SQLException ex) {
            Logger.getLogger(Encargado_comanda.class.getName()).log(Level.SEVERE, null, ex);
        }
        
       

        
    }//GEN-LAST:event_jButton2MouseClicked

    private void milanesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_milanesaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_milanesaActionPerformed

    private void frutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frutaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_frutaActionPerformed

    private void heladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heladoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_heladoActionPerformed

    private void cocaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cocaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cocaActionPerformed

    private void cafeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cafeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cafeActionPerformed

    private void cantidavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidavActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidavActionPerformed

    private void pastaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pastaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pastaActionPerformed

    private void nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nuevoActionPerformed

    private void nuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nuevoMouseClicked
        // TODO add your handling code here:limpiar tabla
      while(tablac.getRowCount()>0){
((DefaultTableModel)tablac.getModel()).removeRow(0);
}JOptionPane.showMessageDialog(null,"Ingresa otro pedido");
    }//GEN-LAST:event_nuevoMouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:modificar
         int FileSelect=tablac.getSelectedRow();
        if(FileSelect>=0){
            JOptionPane.showMessageDialog(null,"Pedido eliminado");
           
             modelo.removeRow(FileSelect);
        }else
        {
            JOptionPane.showMessageDialog(null,"FILA NO SELECIONADA");
        }
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
         int confirmacion= JOptionPane.showConfirmDialog(null,"DESEAS CERRAR TU SESION");
        if(confirmacion==JOptionPane.YES_OPTION){
         Iniciar_Sesion i1=new Iniciar_Sesion();
        i1.setVisible(true);
        dispose();
        }
    }//GEN-LAST:event_jButton3MouseClicked

    private void meseroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meseroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_meseroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Encargado_comanda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Encargado_comanda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Encargado_comanda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Encargado_comanda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Encargado_comanda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Cliente;
    private javax.swing.JCheckBox Whyski;
    private javax.swing.JCheckBox cafe;
    private javax.swing.JComboBox canca;
    private javax.swing.JComboBox cancoca;
    private javax.swing.JComboBox canelote;
    private javax.swing.JComboBox canensalada;
    private javax.swing.JComboBox canflan;
    private javax.swing.JComboBox canfru;
    private javax.swing.JComboBox canhe;
    private javax.swing.JComboBox canmilanesa;
    private javax.swing.JComboBox canpasta;
    private javax.swing.JComboBox canpescado;
    private javax.swing.JComboBox cantidav;
    private javax.swing.JComboBox canwh;
    private javax.swing.JCheckBox coca;
    private javax.swing.JCheckBox elote;
    private javax.swing.JCheckBox ensalada;
    private javax.swing.JCheckBox flan;
    private javax.swing.JLabel fondo;
    private javax.swing.JCheckBox fruta;
    private javax.swing.JCheckBox helado;
    private javax.swing.JLabel id;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox mesa;
    private javax.swing.JTextField mesero;
    private javax.swing.JCheckBox milanesa;
    private javax.swing.JCheckBox nombrev;
    private javax.swing.JButton nuevo;
    public static javax.swing.JTextField numorden;
    private javax.swing.JCheckBox pasta;
    private javax.swing.JCheckBox pescado;
    private javax.swing.JComboBox preca;
    private javax.swing.JComboBox preciov;
    private javax.swing.JComboBox precoca;
    private javax.swing.JComboBox preelote;
    private javax.swing.JComboBox preensalada;
    private javax.swing.JComboBox preflan;
    private javax.swing.JComboBox prefru;
    private javax.swing.JComboBox prehe;
    private javax.swing.JComboBox premilanesa;
    private javax.swing.JComboBox prepasta;
    private javax.swing.JComboBox prepescado;
    private javax.swing.JComboBox pw;
    private javax.swing.JTable tablac;
    // End of variables declaration//GEN-END:variables
}
