/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurante_pro.menu_opciones;

import com.mysql.jdbc.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import restaurante_pro.Iniciar_Sesion;
import restaurante_pro.conectarbd;

/**
 *
 * @author stikeroox
 */
public class registro_empleado extends javax.swing.JFrame {
        DefaultTableModel modelo = new DefaultTableModel();
        PreparedStatement ps;
        ResultSet rs;
    
        
    /**
     * Creates new form registro_empleado
     */
        public void limpiar(){
             Nombre.setText(" ");
        Apellidop.setText("");
        Apellidom.setText("");
        Correo.setText("");
        Contrasena.setText("");
        Clave.setText("");
        Tipousuario.setSelectedItem(" ");
        }
    public registro_empleado() {
        initComponents();
        setLocationRelativeTo( null );
        setTitle("Registro de empleado");
        modelo.addColumn("Clave");
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellidop");
        modelo.addColumn("Apellidom");
        modelo.addColumn("Correo");
        modelo.addColumn("Contrasena");
        modelo.addColumn("Tipousuario");
        
        tablaE.setModel(modelo);
        
    }
    

    /**
     * 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pin = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Nombre = new javax.swing.JTextField();
        Apellidop = new javax.swing.JTextField();
        Apellidom = new javax.swing.JTextField();
        Correo = new javax.swing.JTextField();
        Clave = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Contrasena = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaE = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Tipousuario = new javax.swing.JComboBox();
        buscar = new javax.swing.JButton();
        empleados = new javax.swing.JLabel();
        v1 = new javax.swing.JLabel();
        v2 = new javax.swing.JLabel();
        v3 = new javax.swing.JLabel();
        v44 = new javax.swing.JLabel();
        v5 = new javax.swing.JLabel();
        v6 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Apellido P");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Apellido M");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Correo");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 90, -1));

        pin.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        pin.setForeground(new java.awt.Color(255, 255, 255));
        pin.setText("Clave");
        getContentPane().add(pin, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 90, 30));

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Contraseña");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        Nombre.setBackground(new java.awt.Color(255, 255, 255));
        Nombre.setCaretColor(new java.awt.Color(255, 255, 255));
        Nombre.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Nombre.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        Nombre.setOpaque(false);
        getContentPane().add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 150, -1));

        Apellidop.setOpaque(false);
        getContentPane().add(Apellidop, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 150, -1));

        Apellidom.setOpaque(false);
        getContentPane().add(Apellidom, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 150, -1));

        Correo.setOpaque(false);
        getContentPane().add(Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 150, -1));

        Clave.setOpaque(false);
        getContentPane().add(Clave, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 80, -1));

        jButton1.setText("Nuevo");
        jButton1.setOpaque(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 440, 90, 30));

        jButton2.setText("Registrar");
        jButton2.setOpaque(false);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 440, 150, -1));

        jButton3.setText("Salir");
        jButton3.setOpaque(false);
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 103, 20));

        Contrasena.setOpaque(false);
        getContentPane().add(Contrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 150, -1));

        tablaE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Clave", "nombre", "Apellidop", "Apellidom", "correo", "Contraseña"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablaE.setOpaque(false);
        jScrollPane1.setViewportView(tablaE);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 340, 90));

        jButton4.setText("Modificar");
        jButton4.setOpaque(false);
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 440, 110, 30));

        jButton5.setText("Eliminar");
        jButton5.setOpaque(false);
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 440, 100, -1));

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tipo usuario");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, 20));

        Tipousuario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Administrador", "Camarero", "Cajero", "Chef", "Jefe_almacen" }));
        getContentPane().add(Tipousuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 150, -1));

        buscar.setText("Buscar");
        buscar.setOpaque(false);
        buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscarMouseClicked(evt);
            }
        });
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        getContentPane().add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 80, -1, -1));

        empleados.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        empleados.setForeground(new java.awt.Color(255, 255, 255));
        empleados.setText("Lista de empleados");
        getContentPane().add(empleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, -1, -1));
        getContentPane().add(v1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 100, 20));
        getContentPane().add(v2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 110, 20));
        getContentPane().add(v3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 90, 20));
        getContentPane().add(v44, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 90, 20));
        getContentPane().add(v5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 90, 20));
        getContentPane().add(v6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 90, 20));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurante_pro/imagenes/fondo-con-lineas-azules-375.jpg"))); // NOI18N
        fondo.setText("jLabel14");
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 480));

        txtId.setEditable(false);
        txtId.setEnabled(false);
        getContentPane().add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, 40, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
              
            
    }//GEN-LAST:event_jButton2ActionPerformed
   
    public void validaciones(){
         String Nom ,  Ap = null, Apm = null,  Cor = null,  Con = null, cla = null;
        
      
            
        Nom=Nombre.getText();
        Ap=Apellidop.getText();
        Apm=Apellidom.getText();
        cla=Clave.getText();
        Cor=Correo.getText();
        Con=Contrasena.getText();
            
          try{
             String tel = null;
        validaciones v4=new validaciones( Nom,  Ap,  Apm,  Cor,  Con, cla,tel);
        v1.setText(v4.validar_clave());
        v2.setText(v4.validar_nombre());
        v3.setText(v4.validar_ap());
        v44.setText(v4.validar_am());
        v5.setText(v4.validar_correo());
        v6.setText(v4.validar_pass());
        }catch(Exception e){
            
        }
         
    }
            
    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        //BOTONREGISTRAR
        
         validaciones();
           
          conectarbd con=new conectarbd();
           java.sql.Connection reg=con.getconexion();
             
              
String sql = null;
String nom,ape1,ape2,ide,co,cont,tip,cl;
cl=Clave.getText();
nom=Nombre.getText();
ape1=Apellidop.getText();
ape2=Apellidom.getText();

co=Correo.getText();
cont=Contrasena.getText();

tip=   (String) Tipousuario.getSelectedItem();

       sql=("INSERT INTO registro_empleado(Clave,Nombre,Apellidop,Apellidom,Correo,Contrasena,Tipousuario)VALUES (?,?,?,?,?,?,?)");
    
try {
            
            PreparedStatement pst=reg.prepareStatement(sql);

            pst.setString(1,cl);
            pst.setString(2,nom);
            pst.setString(3,ape1);
            pst.setString(4,ape2);
            pst.setString(5,co);
            pst.setString(6,cont);
            pst.setString(7,tip);
        
             
                

             String DATO[] = new String[7];
            DATO[0] = Clave.getText();
            DATO[1] = Nombre.getText();
            DATO[2] = Apellidop.getText();
            DATO[3] = Apellidom.getText();
            DATO[4] = Correo.getText();
            DATO[5] = Contrasena.getText();
            DATO[6] = Tipousuario.getSelectedItem().toString();
            
            modelo.addRow(DATO);
            int n=pst.executeUpdate();
            if (n>0){
                JOptionPane.showMessageDialog(null,"Registro de empleado exitoso");
                limpiar();
                
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(registro_empleado.class.getName()).log(Level.SEVERE, null, ex);
        }
               

        
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        //modificardatos
       conectarbd con=new conectarbd();
           java.sql.Connection reg=con.getconexion();
        String sql = null;
        try{
           
              PreparedStatement pst=reg.prepareStatement  ("UPDATE registro_empleado SET Clave=?, Nombre=?, Apellidop=?, Apellidom=?,Correo=?, Contrasena=?, Tipousuario=? WHERE id=?");
             
             
              Clave.setText(rs.getString("idempleado"));
               Nombre.setText(rs.getString("Nombre"));
                Apellidop.setText(rs.getString("Apellidop"));
                Apellidom.setText(rs.getString("Apellidom"));
                Correo.setText(rs.getString("Correo"));
                Contrasena.setText(rs.getString("Contrasena"));
                Tipousuario.setSelectedItem(rs.getString("Tipousuario"));
                
            
              
              
              
              
            int res = pst.executeUpdate();
            
            if(res > 0){
                JOptionPane.showMessageDialog(null, "Persona Eliminada");
                        limpiar();

               
            } else {
                 JOptionPane.showMessageDialog(null, "Error al eliminar persona");
                         limpiar();

                 
            }}catch(Exception e){
                
            }
         int FileSelect=tablaE.getSelectedRow();
        if(FileSelect>=0){
             Clave.setText(tablaE.getValueAt(FileSelect, 0).toString());
               Nombre.setText(tablaE.getValueAt(FileSelect, 1).toString());
                Apellidop.setText(tablaE.getValueAt(FileSelect, 2).toString());
                Apellidom.setText(tablaE.getValueAt(FileSelect, 3).toString());
                Correo.setText(tablaE.getValueAt(FileSelect, 4).toString());
                Contrasena.setText(tablaE.getValueAt(FileSelect, 5).toString());
                Tipousuario.setSelectedItem(tablaE.getValueAt(FileSelect, 6).toString());
           
             modelo.removeRow(FileSelect);
        }else
        {
            JOptionPane.showMessageDialog(null,"FILA NO SELECIONADA");
        }
            
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here://boton de eliminar
             conectarbd con=new conectarbd();
           java.sql.Connection reg=con.getconexion();
        String sql = null;
        try{
            
          
           PreparedStatement pst=reg.prepareStatement("DELETE FROM registro_empleado  WHERE idempleado=?");
            pst.setInt(1, Integer.parseInt(txtId.getText()));
              txtId.setText(rs.getString("idempleado"));
               Nombre.setText(rs.getString("Nombre"));
                Apellidop.setText(rs.getString("Apellidop"));
                Apellidom.setText(rs.getString("Apellidom"));
                Correo.setText(rs.getString("Correo"));
                Contrasena.setText(rs.getString("Contrasena"));
                Tipousuario.setSelectedItem(rs.getString("Tipousuario"));
                
            
            int res = pst.executeUpdate();
            
            if(res > 0){
                JOptionPane.showMessageDialog(null, "Persona Eliminada");
                        limpiar();

               
            } else {
                 JOptionPane.showMessageDialog(null, "Error al eliminar persona");
                         limpiar();

                 
            }
            
           
            
        } catch(Exception e){
            System.err.println(e);
        }
         int FileSelect=tablaE.getSelectedRow();
        if(FileSelect>=0){
        
           Clave.setText(tablaE.getValueAt(FileSelect, 0).toString());
               Nombre.setText(tablaE.getValueAt(FileSelect, 1).toString());
                Apellidop.setText(tablaE.getValueAt(FileSelect, 2).toString());
                Apellidom.setText(tablaE.getValueAt(FileSelect, 3).toString());
                Correo.setText(tablaE.getValueAt(FileSelect, 4).toString());
                Contrasena.setText(tablaE.getValueAt(FileSelect, 5).toString());
                Tipousuario.setSelectedItem(tablaE.getValueAt(FileSelect, 6).toString());
           
             modelo.removeRow(FileSelect);
        }else
        {
            JOptionPane.showMessageDialog(null,"FILA NO SELECIONADA");
        }
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add yoHur handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        // TODO add your handling code here:
          
       conectarbd con=new conectarbd();
           java.sql.Connection reg=con.getconexion();
        String sql = null;
        try{
                    
          PreparedStatement pst=reg.prepareStatement("SELECT * FROM registro_empleado WHERE Clave = ?");
          pst.setString(1, Clave.getText());
            
            rs = pst.executeQuery();
            
            if(rs.next()){
                txtId.setText(rs.getString("idempleado"));
               Nombre.setText(rs.getString("Nombre"));
                Apellidop.setText(rs.getString("Apellidop"));
                Apellidom.setText(rs.getString("Apellidom"));
                Correo.setText(rs.getString("Correo"));
                Contrasena.setText(rs.getString("Contrasena"));
                Tipousuario.setSelectedItem(rs.getString("Tipousuario"));
                
             String DATO[] = new String[7];
            DATO[0] = Clave.getText();
            DATO[1] = Nombre.getText();
            DATO[2] = Apellidop.getText();
            DATO[3] = Apellidom.getText();
            DATO[4] = Correo.getText();
            DATO[5] = Contrasena.getText();
            DATO[6] = Tipousuario.getSelectedItem().toString();
            
            modelo.addRow(DATO);
            } else {
                JOptionPane.showMessageDialog(null, "No existe una persona con la clave");
            }
            
        } catch(Exception e){
            System.err.println(e);
        }
    }//GEN-LAST:event_buscarActionPerformed

    private void buscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarMouseClicked
        
    }//GEN-LAST:event_buscarMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
         int confirmacion= JOptionPane.showConfirmDialog(null,"DESEAS CERRAR TU SESION");
        if(confirmacion==JOptionPane.YES_OPTION){
         Iniciar_Sesion i1=new Iniciar_Sesion();
        i1.setVisible(true);
        dispose();
        }
    }//GEN-LAST:event_jButton3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registro_empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registro_empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registro_empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registro_empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registro_empleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Apellidom;
    private javax.swing.JTextField Apellidop;
    private javax.swing.JTextField Clave;
    private javax.swing.JPasswordField Contrasena;
    private javax.swing.JTextField Correo;
    private javax.swing.JTextField Nombre;
    private javax.swing.JComboBox Tipousuario;
    private javax.swing.JButton buscar;
    private javax.swing.JLabel empleados;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel pin;
    private javax.swing.JTable tablaE;
    private javax.swing.JTextField txtId;
    private javax.swing.JLabel v1;
    private javax.swing.JLabel v2;
    private javax.swing.JLabel v3;
    private javax.swing.JLabel v44;
    private javax.swing.JLabel v5;
    private javax.swing.JLabel v6;
    // End of variables declaration//GEN-END:variables

 
}
