/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurante_pro.menu_opciones;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import restaurante_pro.Iniciar_Sesion;
import restaurante_pro.conectarbd;

/**
 *
 * @author stikeroox
 */
public class Registro_provedor extends javax.swing.JFrame {
DefaultTableModel modelo = new DefaultTableModel();
        PreparedStatement ps;
        ResultSet  rs;
    /**
     * Creates new form Registro_provedor
     */
    public Registro_provedor() {
        initComponents();
        setLocationRelativeTo( null );
        modelo.addColumn("Nombre");
        modelo.addColumn("Fecha");
        modelo.addColumn("Razon_social");
        modelo.addColumn("Ciudad");
        modelo.addColumn("Correo");
        modelo.addColumn("Telefono");
        
        Tablan.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tablan = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        Nombre = new javax.swing.JTextField();
        Fecha = new javax.swing.JTextField();
        Razon = new javax.swing.JTextField();
        Ciudad = new javax.swing.JTextField();
        Correo = new javax.swing.JTextField();
        Telefono = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        p1 = new javax.swing.JLabel();
        p2 = new javax.swing.JLabel();
        p3 = new javax.swing.JLabel();
        p4 = new javax.swing.JLabel();
        p5 = new javax.swing.JLabel();
        p6 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jfondo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 674, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 0));

        Tablan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Fecha", "Rason_social", "Ciudad", "Correo", "Telefono"
            }
        ));
        jScrollPane1.setViewportView(Tablan);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 197, 335, 186));

        jLabel4.setText("Razon social");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 247, -1, -1));

        jLabel5.setText("Ciudad");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 289, 72, -1));

        jLabel6.setText("Correo");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 331, -1, -1));

        jLabel3.setText("Fecha");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 205, 56, -1));

        jLabel1.setText("Nombre");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 165, -1, -1));

        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 165, 84, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 157, 104, -1));

        jLabel7.setText("Telefono");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 363, -1, -1));

        jButton1.setText("Nuevo");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, -1, -1));

        jButton2.setText("Registrar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 440, -1, -1));

        jButton3.setText("Eliminar");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 440, -1, -1));

        jButton5.setText("Salir");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 446, 79, -1));
        getContentPane().add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 161, 101, -1));
        getContentPane().add(Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 197, 101, -1));
        getContentPane().add(Razon, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 239, 101, -1));
        getContentPane().add(Ciudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 281, 101, -1));
        getContentPane().add(Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 323, 101, -1));
        getContentPane().add(Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 359, 101, -1));

        jButton4.setText("Buscar");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(545, 153, -1, -1));

        jButton6.setText("Modificar");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 440, -1, -1));
        getContentPane().add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 105, 20));
        getContentPane().add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 201, 105, 20));
        getContentPane().add(p3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 105, 20));
        getContentPane().add(p4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 105, 20));
        getContentPane().add(p5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 105, 20));
        getContentPane().add(p6, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 367, 105, 20));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurante_pro/imagenes/generatedtext (7).png"))); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 370, 70));

        jfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurante_pro/imagenes/fondo-con-lineas-azules-375.jpg"))); // NOI18N
        getContentPane().add(jfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 680, 580));
        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed
    public void validar1(){
       String Hor = null,Fec = null, Raz = null,Ciu = null, Cod = null,Pro = null,Can = null, Pre = null,Sto = null, Nom = null,Ape = null, Apem = null, Cor = null, Con = null, Cla = null,  Tel = null;
       Nom=Nombre.getText();
       Fec=Fecha.getText();
       Raz=Razon.getText();
       Ciu=Ciudad.getText();
       Cor=Correo.getText();
       Tel=Telefono.getText();
                  
        validaciones2 v11=new validaciones2( Hor,Fec, Raz,Ciu, Cod,Pro,Can, Pre,Sto, Nom,Ape, Apem, Cor, Con, Cla,  Tel);
      p1.setText(v11.validar_nombre());
      p2.setText(v11.validar_fe());
      p3.setText(v11.validar_nombre());
      p4.setText(v11.validar_dir());
      p5.setText(v11.validar_correo());
      p6.setText(v11.vali());
    }
    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
     
       conectarbd con=new conectarbd();
       java.sql.Connection reg=con.getconexion();
      
String sql = null;
String nom,f,tre,ci,co,tel;
nom=Nombre.getText();
f=Fecha.getText();
tre=Razon.getText();
ci=Ciudad.getText();
co=Correo.getText();
tel=Telefono.getText();


       sql=("INSERT INTO registroprovedor(Nombre,Fecha,Razon_social,Ciudad,Correo,Telefono)VALUES (?,?,?,?,?,?)");

try {
            
            PreparedStatement pst=reg.prepareStatement(sql);

            pst.setString(1,nom);
            pst.setString(2,f);
            pst.setString(3,tre);
            pst.setString(4,ci);
            pst.setString(5,co);
            pst.setString(6,tel);
            
        
             
                

             String DATO[] = new String[6];
            DATO[0] = Nombre.getText();
            DATO[1] = Fecha.getText();
            DATO[2] = Razon.getText();
            DATO[3] = Ciudad.getText();
            DATO[4] = Correo.getText();
            DATO[5] = Telefono.getText();
           
            
            modelo.addRow(DATO);
            int n=pst.executeUpdate();
            if (n>0){
                JOptionPane.showMessageDialog(null,"registrado con exito");
              
                
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(registro_empleado.class.getName()).log(Level.SEVERE, null, ex);
        }

    
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
         int confirmacion= JOptionPane.showConfirmDialog(null,"Deseas regresar al menu principal");
        if(confirmacion==JOptionPane.YES_OPTION){
         menu_administrador a1=new menu_administrador();
        a1.setVisible(true);
        dispose();
        }
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro_provedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro_provedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro_provedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro_provedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro_provedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Ciudad;
    private javax.swing.JTextField Correo;
    private javax.swing.JTextField Fecha;
    private javax.swing.JTextField Nombre;
    private javax.swing.JTextField Razon;
    private javax.swing.JTable Tablan;
    private javax.swing.JTextField Telefono;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel jfondo;
    private javax.swing.JLabel p1;
    private javax.swing.JLabel p2;
    private javax.swing.JLabel p3;
    private javax.swing.JLabel p4;
    private javax.swing.JLabel p5;
    private javax.swing.JLabel p6;
    // End of variables declaration//GEN-END:variables
}
