/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurante_pro.menu_opciones;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import restaurante_pro.Iniciar_Sesion;
import restaurante_pro.conectarbd;

/**
 *
 * @author stikeroox
 */
public class Reservacion_comensal extends javax.swing.JFrame {
   
    /**
     * Creates new form Reservacion_comensal
     */
    public Reservacion_comensal() {
        initComponents();
        setTitle("Reserva");
        setLocationRelativeTo( null );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        NUMEROC = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        FUMADOR = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Telefono = new javax.swing.JTextField();
        rs1 = new javax.swing.JLabel();
        rs2 = new javax.swing.JLabel();
        rs3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        Hora = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Fecha ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 245, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 120, -1, -1));
        getContentPane().add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 112, 131, -1));

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Hora");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 196, 110, -1));

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("N.comensales");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 284, -1, -1));

        NUMEROC.setEditable(true);
        NUMEROC.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        NUMEROC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NUMEROCActionPerformed(evt);
            }
        });
        getContentPane().add(NUMEROC, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 279, 131, -1));

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tipo de mesa");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 328, 135, -1));

        FUMADOR.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Fumador", "No Fumador" }));
        getContentPane().add(FUMADOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 323, 131, -1));

        jButton1.setText("Nuevo");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, 84, -1));

        jButton2.setText("Registrar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, 91, -1));

        jButton3.setText("Salir");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 93, -1));

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Telefono");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 160, -1, -1));
        getContentPane().add(Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 152, 131, -1));
        getContentPane().add(rs1, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 116, 91, 20));
        getContentPane().add(rs2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 91, 20));
        getContentPane().add(rs3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 91, 20));

        jButton4.setText("Modificar");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 430, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurante_pro/iconos/generatedtext (12).png"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 220, 110));

        Hora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HoraActionPerformed(evt);
            }
        });
        getContentPane().add(Hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 130, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurante_pro/imagenes/desktopwallpapers.org.ua-8389.jpg"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NUMEROCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NUMEROCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NUMEROCActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed
   public void val(){
          String Hor,Fec = null, Raz = null,Ciu = null, Cod = null,Pro = null,Can = null, Pre = null,Sto = null, Nom,Ape = null, Apem = null, Cor = null, Con = null, Cla = null,  Tel = null;
           Nom=Nombre.getText();
        
           Hor=Hora.getText();
           Tel=Telefono.getText();
           
           validaciones2 v2=new validaciones2( Hor,Fec, Raz,Ciu, Cod,Pro,Can, Pre,Sto, Nom,Ape, Apem, Cor, Con, Cla,  Tel);
          try{
              rs1.setText(v2.validar_nombre());
              rs2.setText(v2.vali());
              rs3.setText(v2.validar_hora());
              
          }catch(Exception e){
              
          }
   }
    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here: boton registrar reserva
                 val();
        JOptionPane.showMessageDialog(null,"campos vacios");
             conectarbd con=new conectarbd();
Connection reg=con.getconexion();
DateFormat dat=new SimpleDateFormat("yyyy-MM-dd");

String nom,tel,h,f,noc,ti,nm;
String sql;
nom=Nombre.getText();
tel=Telefono.getText();
h=Hora.getText();
f=dat.format(CALENDAR.getDate());
noc=NUMEROC.getSelectedItem().toString();
ti=FUMADOR.getSelectedItem().toString();

sql="INSERT INTO reservacliente (Nombre,Telefono,Hora,Fecha,No_comensales,Tipo_mesa)VALUES (?,?,?,?,?,?)";
        try {
          
            PreparedStatement pst=reg.prepareStatement(sql);
            pst.setString(1,nom);
            pst.setString(2,tel);
            pst.setString(3,h);
            pst.setString(4,f);
            pst.setString(5,noc);
            pst.setString(6,ti);
           
          
            int n=pst.executeUpdate();
            if (n>0){
                JOptionPane.showMessageDialog(null,"RESERVACION EXITOSA");
                
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Reservacion_comensal.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println(f);
                System.out.println(h);

    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
         int confirmacion= JOptionPane.showConfirmDialog(null,"DESEAS CERRAR TU SESION");
        if(confirmacion==JOptionPane.YES_OPTION){
         Iniciar_Sesion i1=new Iniciar_Sesion();
        i1.setVisible(true);
        dispose();
        }
    }//GEN-LAST:event_jButton3MouseClicked

    private void HoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HoraActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reservacion_comensal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reservacion_comensal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reservacion_comensal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reservacion_comensal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reservacion_comensal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox FUMADOR;
    private javax.swing.JTextField Hora;
    private javax.swing.JComboBox NUMEROC;
    private javax.swing.JTextField Nombre;
    private javax.swing.JTextField Telefono;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel rs1;
    private javax.swing.JLabel rs2;
    private javax.swing.JLabel rs3;
    // End of variables declaration//GEN-END:variables
}
